;; SPDX-License-Identifier: GPL-3.0-or-later

(in-package #:nucleotide)

(defconstant +xk-return+ #xff0d)
(defconstant +mod-shift+ 1)
(defconstant +mod-ctrl+ 4)
(defconstant +mod-super+ 64)

(defun spawn (command)
  (uiop:launch-program (list "setsid" "-f" command)))

(defun bind-key (wm keysym modifiers action)
  (let ((binding (river-xkb-bindings-v1.get-xkb-binding
		  (wm-xkb wm) (wm-seat wm) keysym modifiers)))
    (push (lambda (event &rest args)
	    (declare (ignore args))
	    (when (eq event :pressed) (funcall action)))
	  (proxy-hooks binding))
    (push binding (wm-pending-bindings wm))
    (river-window-manager-v1.manage-dirty (wm-river wm))
    binding))

(defun bind-key-chord (wm submap keysym action)
  (let ((binding (river-xkb-bindings-v1.get-xkb-binding (wm-xkb wm) (wm-seat wm) keysym 0)))
    (push (lambda (event &rest args)
	    (declare (ignore args))
	    (when (eq event :pressed)
	      (leave-submap wm)
	      (funcall action)))
	  (proxy-hooks binding))
    (push binding (submap-bindings submap))
    binding))

(defun shiftify (modifier)
  (logior modifier +mod-shift+))

(defun keybinds (wm)
  (macrolet ((def-keybind (key mod &body body)
	       `(bind-key wm ,(if (characterp key)
				  `(char-code ,key)
				  key) ,mod (lambda () ,@body)))
	     (def-chord ((key mod) &body chords)
	       (let ((submap (gensym "SUBMAP")))
		 `(let ((,submap (make-submap)))
		    ,@(loop for (ckey . body) in chords
			    collect `(bind-key-chord wm ,submap
						     ,(if (characterp ckey)
							  `(char-code ,ckey)
							  ckey)
						     (lambda () ,@body)))
		    (bind-key wm ,(if (characterp key)
				      `(char-code ,key)
				      key)
			      ,mod (lambda () (enter-submap wm ,submap)))))))
    (def-keybind +xk-return+ (shiftify +mod-super+) (spawn "alacritty"))
    (def-keybind #\p +mod-super+ (spawn "bemenu-run"))
    (def-keybind #\k +mod-super+ (cycle-focus wm :prev))
    (def-keybind #\l +mod-super+ (cycle-focus wm :next))
    (def-keybind #\k (shiftify +mod-super+) (move-window wm :prev))
    (def-keybind #\l (shiftify +mod-super+) (move-window wm :next))
    (def-keybind #\c (shiftify +mod-super+) (close-focused wm))
    (def-keybind #\q +mod-super+ (exit wm))
    (def-chord (#\Space +mod-super+) (#\e (toggle-highlight wm "emacs")))
    (loop for ws in (wm-workspaces wm)
	  for key from (char-code #\1)
	  do (let ((ws ws))
	       (def-keybind key +mod-super+ (switch-workspace wm ws))
	       (def-keybind key (shiftify +mod-super+) (send-to-workspace wm ws))))))
